### ISSUE TITLE
ecsk cp fails to download file

### ISSUE THREAD

**Issue by jkrmelj** [yukiarrr/ecsk#14]
Recently ecsk cp stopped to work on my environment. The problems could be related to upgrading AWS CLI to latest version recently.

So the command 
ecsk cp <container name>:<remote file name> ./

results in the following error:
```
Starting session with SessionId: ecs-execute-command-0513da50ff4d69207
operation error S3: PutObject, failed to resolve service endpoint, an AWS region is required, but was not found


Exiting session with sessionId: ecs-execute-command-0513da50ff4d69207.
```

This error is shown just after temporary S3 bucket is chosen in the download procedure.

Even if I was trying to add 
[default]
region=eu-central-1
into .aws/config

or export AWS_REGION=eu-central-1 prior to execute command, the problem persisted.

ecsk --version
ecsk version v0.9.1

aws --version
aws-cli/2.13.9 Python/3.11.4 Darwin/21.6.0 exe/x86_64 prompt/off

Any idea why this is happening?

**Comment by yukiarrr** [comment]
Thanks for the issue!
Since it is failing after `Starting session with SessionId`, there is most likely a problem on the ECS Task side to which you are connecting.
May I ask you to check AWS_REGION on the ECS Task side?

**Comment by jkrmelj** [comment]
That's correct. After adding AWS_REGION as environment variable to ECS task, cp started to work. Thank you.
